---
abstract: 'Tapper - dependencies for central server'
author:
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Tapper-Server
requires:
  DBD::Pg: 0
  DBD::SQLite: 0
  DBD::mysql: 0
  DBI: 0
  File::Copy::Recursive: 0
  File::Slurp: 0
  IO::Interactive: 0
  Module::Install::Catalyst: 0
  Tapper::CLI: 0
  Tapper::Config: 0
  Tapper::Reports::API: 0
  Tapper::Reports::Receiver: 0
  Tapper::Reports::Web: 0
  Tapper::TAP::Harness: 0
  Tapper::Testplan: 0
  Template::Plugin::Autoformat: 0
  Test::WWW::Mechanize: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Task-Tapper-Server
  homepage: http://metacpan.org/release/Task-Tapper-Server
  repository: git://github.com/amd/Task-Tapper-Server.git
version: 0.001
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@AMD/GatherDir'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@AMD/PruneCruft'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@AMD/ManifestSkip'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@AMD/MetaYAML'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@AMD/Readme'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@AMD/ExtraTests'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@AMD/ExecDir'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@AMD/ShareDir'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@AMD/MakeMaker'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@AMD/Manifest'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@AMD/TestRelease'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@AMD/ConfirmRelease'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@AMD/UploadToCPAN'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@AMD/MetaConfig'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@AMD/MetaJSON'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@AMD/PkgVersion'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@AMD/PodSyntaxTests'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@AMD/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@AMD/PodCoverageTests'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@AMD/MetaResources'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@AMD/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@AMD/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::TaskWeaver
      name: '@AMD/TaskWeaver'
      version: 0.101624
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@AMD/AutoPrereqs'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: '@AMD/Git::Describe'
      version: 0.001
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@AMD/CheckChangesHasContent'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@AMD/NextRelease'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@AMD/Git::CheckFor::CorrectBranch'
      version: 0.004
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@AMD/Git::NextVersion'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@AMD/@Git/Check'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@AMD/@Git/Commit'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@AMD/@Git/Tag'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@AMD/@Git/Push'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300020
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300020
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300020
x_authority: cpan:AMD
